import coreWebVitals from 'eslint-config-next/core-web-vitals';
import typescript from 'eslint-config-next/typescript';

const config = [
  ...coreWebVitals,
  ...typescript,
  // next-env.d.ts is generated by Next on every build.
  // Vendored third-party code is not ours to lint or restyle.
  { ignores: ['.next/**', 'node_modules/**', 'scripts/**', 'next-env.d.ts', 'src/lib/vendor/**'] },
];

export default config;
